name: Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on:
      - self-hosted
      - Linux
      - x64


    steps:
      - name: Check runner
        run : |
          hostname
          pwd
          java -version